
name: Github Drowned Moses
on: push
jobs:
  Build-app:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/drowned-moses
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Moses Up
        run: |
          cd ${{ github.workspace }}/moses-linux
          echo "${{ github.workspace }}/moses-linux" >> $GITHUB_PATH
          ./moses &
          sleep 15
      -
        name: EULA Accept
        run: |
          tdskt platforms
          tdskt eula nxp-la-opt-v5 setprop accepted true
          tdskt platforms
      -
        name: Enable Emulation
        run: |
          tdskt -p enableemulation
      -
        name: Load Application
        run: |
          APPID=$(tdskt load ./appconfig_0/)
          echo "APPID=$APPID" >> $GITHUB_ENV
      -
        name: Build SDK Container
        run: |
          tdskt -p application ${{ env.APPID }} runsdk release
      -
        name: Build Application
        run: |
          docker run --rm -t \
            -v ${PWD}:/app \
            -e AR="aarch64-linux-gnu-ar" \
            -e AS="aarch64-linux-gnu-as" \
            -e CC="aarch64-linux-gnu-gcc" \
            -e CXX="aarch64-linux-gnu-g++" \
            -e CPP="aarch64-linux-gnu-cpp" \
            -e STRIP="aarch64-linux-gnu-strip" \
            -e LD="aarch64-linux-gnu-ld" \
            -e CROSS_COMPILE="aarch64-linux-gnu-" \
            -e QMAKE="aarch64-linux-gnu-qmake" \
            -e QT_INCLUDES="/usr/include/aarch64-linux-gnu/qt5" \
            -e QMAKE_DESTIDIR='/app/appconfig_0/work/drowned-moses' \
            drowned-moses_arm64v8-qt5-vivante-no-ssh_bullseye_release_${APPID}_sdk_image \
            bash -c "cd /app && aarch64-linux-gnu-qmake drowned-moses.pro && make"
      -
        name: Build Release Container
        run: |
          tdskt -p application ${{ env.APPID }} build release
      -
        name: Dockerhub
        run: |
          docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}
          docker tag \
            drowned-moses_arm64v8-qt5-vivante-no-ssh_bullseye_release_${{ env.APPID }}:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/drowned-moses:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/drowned-moses:latest
