
name: Github Drowned Moses
on: push
jobs:
  Update-Application:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build moses Container
        uses: actions/checkout@v2
        run: cat ${{ github.workspace }}/README.md
