
name: Github Drowned Moses
on: push
jobs:
  Update-moses:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Build Moses container and push
        run: |
          cd ${{ github.workspace }}
          cat README.md
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/moses .
          docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/moses
  Build-app:
    needs: Update-moses
    runs-on: ubuntu-latest
    container: { image: matheuscastello/moses }
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      - 
        name: Moses up and run
        run: |
          cd /moses-linux
          ./moses &
          sleep 30
          ./tdskt platforms
